language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt --allow-external
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=Goulib
after_success:
  coveralls
