language: python
python:
  - 2.7
install:
  - pip install --allow-all-external -r requirements.txt 
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=Goulib
after_success:
  coveralls
